export const CONTAINER: symbol = Symbol('__container__')
export const ORIGINAL_CTOR: symbol = Symbol('__original_ctor__')
export const RESOLVER: symbol = Symbol('__resolver__')
export const APP_ROOT: symbol = Symbol('__app_root__')
export const BOOTSTRAP_HANDLERS: symbol = Symbol('__bootstrap_handlers__')
